name: Java CI with Gradle

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  # 소스코드의 테스트를 진행하는 Job
  test:
    runs-on: ubuntu-latest
    steps:
      # 소스코드 가져오기
      - uses: actions/checkout@v4
      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
      # Action에 전달할 인자
        with:
          java-version: '17'
          distribution: 'temurin'
      # Gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      # Gradle Wrapper로 테스트 진행
      - name: Test with Gradle Wrapper
        run: ./gradlew test